"use strict";

// No server, external libraries, or network requests. Replace mockAnalysis with an API later.
const fields = [
  ['alone','독거 여부',['아니오','예']],
  ['chronic','만성질환 수',['0개','1개','2개','3개 이상']],
  ['mobility','이동 어려움',['없음','보통','심함']],
  ['decline','최근 건강 악화',['없음','있음']],
  ['family','가족 연락 빈도',['거의 없음','가끔','자주']],
  ['social','사회적 교류 정도',['거의 없음','보통','활발']],
  ['mood','우울·무기력 정도',['낮음','보통','높음']],
  ['housing','주거 안전 상태',['양호','주의','위험']],
  ['days','마지막 방문 후 경과일',null,'일'],
  ['missed','최근 연락 미응답 횟수',['0회','1회','2회 이상']]
];
const types=['안정형','건강취약형','사회고립형','복합돌봄취약형'];
const seeds=[
  ['p1','김○○','중앙동',1,3,2,1,0,0,2,1,24,2],
  ['p2','박○○','행복동',1,1,0,0,0,0,1,0,18,1],
  ['p3','이○○','중앙동',0,3,2,1,2,1,0,0,12,0],
  ['p4','최○○','푸른동',1,1,0,0,2,2,0,0,4,0],
  ['p5','정○○','행복동',1,2,1,0,1,0,2,1,21,2],
  ['p6','윤○○','푸른동',0,0,0,0,2,2,0,0,3,0]
].map(([id,name,area,...values])=>({id,name,area,...Object.fromEntries(fields.map((f,i)=>[f[0],values[i]]))}));
const storageKey='ondol-prototype-v1';
let people=structuredClone(seeds), storageAvailable=true;
function validPerson(p){return p && typeof p.id==='string' && typeof p.name==='string' && p.name.trim().length>0 && typeof p.area==='string' && fields.every(([k,,options])=>Number.isInteger(p[k]) && p[k]>=0 && p[k]<=(options?options.length-1:3650));}
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(Array.isArray(saved)&&saved.length&&saved.every(validPerson)&&new Set(saved.map(p=>p.id)).size===saved.length)people=saved;}catch{storageAvailable=false;}
let selectedId=people[0].id, page='dashboard', query='', filter='', editId=null, toastTimer;
const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const selected=()=>people.find(p=>p.id===selectedId)||people[0];
function save(){try{localStorage.setItem(storageKey,JSON.stringify(people));return true;}catch{storageAvailable=false;return false;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}

function badge(p){const r=mockAnalysis(p);return `<span class="badge ${['','health','social','complex'][r.index]}">${r.type}</span>`;}
function head(title,description,action=''){return `<div class="page-head"><div><div class="eyebrow">CARE WORKSPACE</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
// v2: presentation score and visit rules are transparent demonstration policy, not clinical advice.
const dayKey=()=>new Date().toLocaleDateString('en-CA');
let role='admin', dirty=false, pending=null, photoDraft='', order='score', visitsOnly=false, currentURL=location.href;
const exampleProfiles=[['여성','1947-03-12','중앙동 돌봄로 12, 101호','고혈압, 당뇨, 관절염'],['남성','1950-08-21','행복동 나눔길 8, 202호','고혈압'],['여성','1944-11-04','중앙동 돌봄로 24, 301호','당뇨, 관절염, 심장질환'],['남성','1952-05-17','푸른동 이웃길 9, 102호','고혈압'],['여성','1948-07-09','행복동 나눔길 18, 201호','고혈압, 관절염'],['남성','1951-02-25','푸른동 이웃길 22, 103호','없음']];
people=people.map(p=>{const i=seeds.findIndex(s=>s.id===p.id),v=exampleProfiles[i];return {gender:v?.[0]||'미입력',birth:v?.[1]||'',address:v?.[2]||p.area,history:v?.[3]||'',phone:'',contact:'',comment:'',photo:'',visited:'',updated:'',...p};});
function score(p){
 const parts=[['생활',p.alone*10,10],['건강',p.chronic/3*10+p.mobility/2*10+p.decline*10,30],['관계',(2-p.family)*5+(2-p.social)*5,20],['정서',p.mood*5,10],['주거',p.housing*5,10],['돌봄 공백',Math.min(p.days,30)/3+p.missed*5,20]];
 const total=Math.round(parts.reduce((a,v)=>a+v[1],0));
 const top=[...parts].sort((a,b)=>b[1]/b[2]-a[1]/a[2]).filter(v=>v[1]>0).slice(0,2);
 return {total,parts,line:top.length?`${top.map(v=>v[0]).join('·')} 항목의 확인 필요가 상대적으로 높습니다.`:'입력된 항목의 점수는 모두 0점입니다. 정기 확인을 이어가세요.'};
}
function due(p){return score(p).total>=60||p.missed===2||p.days>=14;}
function visitReason(p){return [score(p).total>=60?'점수 60점 이상':'',p.missed===2?'미응답 2회 이상':'',p.days>=14?'방문 공백 14일 이상':''].filter(Boolean).join(' · ');}
function ranked(){return [...people].sort((a,b)=>score(b).total-score(a).total||b.days-a.days);}
function mockAnalysis(p){const h=p.chronic>=2||p.mobility===2||p.decline===1,s=p.family===0||p.social===0,o=p.mood===2,j=p.housing===2;const n=[h,s,o,j].filter(Boolean).length;const index=n>=2?3:h?1:s?2:0;return {index,type:n===1&&!h&&!s?'유형 확인 필요':types[index],probability:[88,79,84,82][index],reasons:score(p).parts.filter(v=>v[1]>0).map(v=>[v[0],`${Math.round(v[1]*10)/10} / ${v[2]}점`])};}
function portrait(p,large=false){const src=p.photo;if(/^data:image\/(png|jpeg|webp);base64,/.test(src||''))return `<img class="portrait ${large?'large':''}" src="${esc(src)}" alt="${esc(p.name)} 대상자 사진">`;return `<span class="portrait placeholder ${large?'large':''}" role="img" aria-label="${esc(p.name)} 사진 미등록"><svg viewBox="0 0 80 90" aria-hidden="true"><circle cx="40" cy="29" r="16"/><path d="M10 87V76a30 30 0 0 1 60 0v11"/></svg>${large?'<small>사진 미등록</small>':''}</span>`;}
function totalBadge(p){return `<span class="score-number">${score(p).total}<small>/ 100점</small></span>`;}
function ring(p){const n=score(p).total;return `<div class="score-ring" style="--value:${n}%"><div><strong>${n}</strong><span>/ 100점</span></div></div>`;}
function barRows(parts){return `<div class="bar-rows">${parts.map(([label,value,max])=>`<div class="bar-item"><div><span>${label}</span><strong>${Math.round(value*10)/10}<small> / ${max}점</small></strong></div><div class="track"><span style="width:${value/max*100}%"></span></div></div>`).join('')}</div>`;}
function radar(p){const a=score(p).parts;const point=(i,r)=>[160+Math.cos(-Math.PI/2+i*Math.PI/3)*r,145+Math.sin(-Math.PI/2+i*Math.PI/3)*r];const poly=r=>a.map((_,i)=>point(i,r).join(',')).join(' ');return `<svg class="radar" viewBox="0 0 320 300" role="img" aria-label="6개 영역별 점수 비율, 값이 클수록 확인 필요 항목이 많음"><title>${a.map(v=>`${v[0]} ${Math.round(v[1]/v[2]*100)}%`).join(', ')}</title>${[25,50,75,100].map(r=>`<polygon points="${poly(r)}" fill="none" stroke="#dae2ec"/>`).join('')}${a.map((_,i)=>`<line x1="160" y1="145" x2="${point(i,100)[0]}" y2="${point(i,100)[1]}" stroke="#dae2ec"/>`).join('')}<polygon points="${a.map((v,i)=>point(i,v[1]/v[2]*100).join(',')).join(' ')}" fill="#4775eb33" stroke="#4775eb" stroke-width="2.5"/>${a.map((v,i)=>`<text x="${point(i,125)[0]}" y="${point(i,125)[1]}" text-anchor="middle" dominant-baseline="middle">${v[0]}</text>`).join('')}<text x="164" y="72" class="scale">75%</text><text x="164" y="122" class="scale">25%</text></svg>`;}
function policy(){return `<details class="policy"><summary>점수·방문 인원은 어떻게 계산하나요?</summary><p>시연용 돌봄 확인 점수이며 실제 위험도·진단·AI 확률이 아닙니다. 점수가 높을수록 입력된 확인 항목이 많습니다.</p><ul><li>생활 10점: 독거 10점</li><li>건강 30점: 질환 수(3개 이상=10점), 이동 어려움(심함=10점), 건강 악화(있음=10점)</li><li>관계 20점: 가족 연락·사회 교류 각각 거의 없음 10점, 중간 5점, 잦음·활발 0점</li><li>정서·주거 각각 10점: 낮음·양호 0점, 보통·주의 5점, 높음·위험 10점</li><li>돌봄 공백 20점: 방문 경과일÷30×10(최대 10점) + 미응답 0/1/2회 이상에 0/5/10점</li></ul><p>질환 수와 이동 어려움은 각 최대 범주에 비례합니다. 합계를 반올림해 100점 만점으로 표시합니다. 방문 제안은 60점 이상 또는 미응답 2회 이상 또는 방문 공백 14일 이상인 대상자 중 오늘 방문 완료하지 않은 사람입니다. 인력·이동 시간은 반영하지 않습니다. 기준은 기획안의 확정 기준이 아닌 시연용 가정입니다.</p></details>`;}
function strip(){const done=people.filter(p=>p.visited===dayKey()),left=people.filter(p=>due(p)&&p.visited!==dayKey());$('#visit-strip').innerHTML=`<div><span class="status-dot"></span><strong>오늘 방문 제안 <b>${left.length}</b>명</strong><span>방문 완료 ${done.length}명 · 전체 ${people.length}명</span></div><button data-action="visits">방문 대상 확인 →</button>`;}
function table(list,rank=false){return `<div class="person-list">${list.map((p,i)=>`<article class="person-row">${rank?`<span class="rank">${String(i+1).padStart(2,'0')}</span>`:''}<div class="person">${portrait(p)}<div><button class="name-button" data-person="${esc(p.id)}">${esc(p.name)}</button><small>${esc(p.gender)} · ${esc(p.area)}</small></div></div><div class="row-insight">${badge(p)}<p>${esc(p.comment||score(p).line)}</p></div><div class="row-score">${totalBadge(p)}<small>${p.visited===dayKey()?'오늘 방문 완료':due(p)?'오늘 방문 제안':'정기 확인'}</small></div><button data-person="${esc(p.id)}">상세 보기</button></article>`).join('')}</div>`;}
function dashboard(){const avg=Math.round(people.reduce((a,p)=>a+score(p).total,0)/people.length);return head('오늘의 돌봄 현황','숫자로 살피고, 사람에게 집중하세요.',role==='admin'?'<button class="primary" data-nav="form">＋ 대상자 등록</button>':'')+`<div class="stats"><div class="stat"><span>전체 대상자</span><strong>${people.length}<em>명</em></strong><small>현재 관리 중인 이웃</small></div><div class="stat"><span>평균 확인 점수</span><strong>${avg}<em>/ 100점</em></strong><small>입력된 돌봄 항목 기준</small></div><div class="stat"><span>오늘 방문 완료</span><strong>${people.filter(p=>p.visited===dayKey()).length}<em>명</em></strong><small>오늘 완료로 기록한 대상자</small></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>대상자별 돌봄 확인 점수</h2><p>전체 대상자 · 높은 점수 순 · 100점 만점</p></div><span class="badge">시연용 지표</span></div><div class="comparison">${ranked().map(p=>`<button class="compare-row" data-person="${esc(p.id)}"><span>${esc(p.name)}</span><div class="track"><span style="width:${score(p).total}%"></span></div><strong>${score(p).total}</strong></button>`).join('')}</div></section><section class="panel distribution"><h2>돌봄 유형 분포</h2><p class="muted">전체 ${people.length}명 · 예시 분류</p>${[...types,'유형 확인 필요'].map(t=>{const n=people.filter(p=>mockAnalysis(p).type===t).length;return `<div class="dist-row"><span>${t}</span><strong>${n}명</strong><div class="track"><span style="width:${n/people.length*100}%"></span></div></div>`;}).join('')}</section></div><section class="panel"><div class="panel-head"><div><h2>우선 살펴볼 대상자</h2><p>돌봄 확인 점수 순 · 개인별 한줄 평</p></div><button data-nav="people">전체 보기 →</button></div>${table(ranked().slice(0,5),true)}</section>${policy()}`;}
function peoplePage(){return head('대상자 관리','개인 정보와 돌봄 현황을 한곳에서 확인하세요.',role==='admin'?'<button class="primary" data-nav="form">＋ 대상자 등록</button>':'')+`<section class="panel"><div class="toolbar"><input id="search" type="search" aria-label="이름 또는 주소 검색" placeholder="이름 · 지역 · 주소 검색" value="${esc(query)}"><select id="filter" aria-label="유형 필터"><option value="">모든 유형</option>${[...types,'유형 확인 필요'].map(t=>`<option ${filter===t?'selected':''}>${t}</option>`).join('')}</select><select id="order" aria-label="정렬"><option value="score" ${order==='score'?'selected':''}>점수 높은 순</option><option value="name" ${order==='name'?'selected':''}>이름순</option></select><button data-action="clear">조건 초기화</button></div><label class="check"><input id="visits-only" type="checkbox" ${visitsOnly?'checked':''}>오늘 방문 제안만 보기</label><div id="people-table"></div></section>`;}
function updateTable(){let list=people.filter(p=>(p.name+' '+p.area+' '+p.address).includes(query)&&(!filter||mockAnalysis(p).type===filter)&&(!visitsOnly||due(p)&&p.visited!==dayKey()));list.sort(order==='score'?(a,b)=>score(b).total-score(a).total:(a,b)=>a.name.localeCompare(b.name));$('#people-table').innerHTML=`<p class="muted result-count">${list.length}명의 대상자</p>`+(list.length?table(list):'<div class="empty"><h2>조건에 맞는 대상자가 없습니다</h2><p>검색어와 필터를 변경하거나 조건을 초기화하세요.</p><button data-action="clear">조건 초기화</button></div>');}
function identity(p){return `<section class="panel resume"><div class="resume-header">${portrait(p,true)}<div><span class="eyebrow">CARE PROFILE · ${esc(p.id)}</span><h2>${esc(p.name)}</h2><p>${esc(p.gender)} · ${esc(p.birth||'생년월일 미입력')}</p>${badge(p)}<small>신상정보는 시연용 가상 정보입니다.</small></div></div><dl class="details"><div><dt>주소</dt><dd>${esc(p.address||'미입력')}</dd></div><div><dt>연락처</dt><dd>${esc(p.phone||'미입력')}</dd></div><div><dt>보호자 · 비상 연락</dt><dd>${esc(p.contact||'미입력')}</dd></div><div><dt>병력</dt><dd>${esc(p.history||'미입력')}</dd></div></dl><div class="comment-box"><span>${p.comment?'관리자 한줄 평':'자동 한줄 평'}</span><p>${esc(p.comment||score(p).line)}</p>${p.comment?`<small>자동 점수 설명: ${esc(score(p).line)}</small>`:''}</div></section>`;}
function detail(){const p=selected();return head('대상자 상세','신상정보 · 돌봄 상태 · 방문 기록',role==='admin'?'<button data-action="edit" class="primary">프로필·한줄 평 편집</button>':'<span class="badge">조회 전용</span>')+`<div class="two-col">${identity(p)}<section class="panel score-card"><div class="panel-head"><h2>돌봄 확인 점수</h2><span class="badge">시연용</span></div>${ring(p)}<p>${esc(score(p).line)}</p><button class="primary" data-nav="analysis">영역별 분석 보기 →</button></section></div><div class="two-col"><section class="panel"><h2>생활 · 건강 · 돌봄 항목</h2><dl class="details">${fields.map(([k,l,o,u])=>`<div><dt>${l}</dt><dd>${o?o[p[k]]:p[k]+u}</dd></div>`).join('')}</dl></section><section class="panel"><h2>오늘의 방문</h2><p class="visit-label">${p.visited===dayKey()?'오늘 방문 완료':due(p)?'방문 제안 대상':'정기 확인 대상'}</p><p>${p.visited===dayKey()?'오늘 방문 완료로 기록했습니다.':esc(visitReason(p)||'현재 방문 제안 조건에 해당하지 않습니다.')}</p><p class="muted">방문 후 ${p.days}일 · 최근 미응답 ${fields[9][2][p.missed]}</p>${role==='admin'?`<button data-action="visit" class="primary">${p.visited===dayKey()?'오늘 방문 완료 취소':'오늘 방문 완료로 기록'}</button>`:''}<p class="note">완료 기록은 오늘의 남은 인원에 반영됩니다. 건강·연락 상태와 방문 경과일 입력값은 별도로 수정하세요.</p></section></div><button data-nav="people">← 대상자 목록</button>`;}
function analysis(){const p=selected();return head('돌봄 분석','총점과 영역별 기여도를 함께 확인하세요.')+`<section class="panel analysis-selector"><label for="analysis-person">대상자 선택</label><select id="analysis-person">${people.map(v=>`<option value="${esc(v.id)}" ${v.id===p.id?'selected':''}>${esc(v.name)} · ${esc(v.area)}</option>`).join('')}</select><button data-nav="detail">프로필 보기</button></section><div class="analysis-grid"><section class="panel score-card"><h2>${esc(p.name)} 님의 확인 점수</h2>${ring(p)}${badge(p)}<p>${esc(p.comment||score(p).line)}</p><small>관리자 평과 별개로 점수는 입력값에서 자동 계산됩니다.</small></section><section class="panel"><h2>돌봄 특성 방사형 그래프</h2><p class="muted">각 영역 만점 대비 비율 · 바깥쪽일수록 높음</p>${radar(p)}</section><section class="panel"><h2>총점에 기여한 항목</h2><p class="muted">6개 영역의 합계 = ${score(p).total}점 (반올림)</p>${barRows(score(p).parts)}</section></div>${policy()}`;}
function formPage(){const p=editId?selected():{name:'',area:'',gender:'미입력',birth:'',address:'',history:'',phone:'',contact:'',comment:'',photo:'',alone:0,chronic:0,mobility:0,decline:0,family:2,social:2,mood:0,housing:0,days:0,missed:0};photoDraft=p.photo;return head(editId?'대상자 프로필 편집':'새 대상자 등록','필수 항목 * · 저장 전까지 기존 정보는 변경되지 않습니다.')+`<form id="person-form" class="panel"><div id="save-error" role="alert"></div><fieldset><legend>01 신상정보</legend><div class="photo-editor"><div id="photo-preview">${portrait(p,true)}</div><div><label>사진 선택 (선택)<input type="file" id="photo" accept="image/png,image/jpeg,image/webp" aria-describedby="photo-help"></label><small id="photo-help">JPG·PNG·WebP, 최대 2MB. 선택한 사진은 이 브라우저에만 저장됩니다.</small><p id="photo-error" role="alert"></p><button type="button" data-action="remove-photo">사진 제거</button></div></div><div class="form-grid">${[['name','이름 *',30],['area','거주 지역',40],['address','상세 주소',150],['phone','연락처',30],['contact','보호자·비상 연락',100]].map(([k,l,max])=>`<label>${l}<input name="${k}" ${k==='name'?'required':''} maxlength="${max}" value="${esc(p[k])}"></label>`).join('')}<label>성별<select name="gender">${['미입력','여성','남성','기타'].map(v=>`<option ${p.gender===v?'selected':''}>${v}</option>`).join('')}</select></label><label>생년월일<input name="birth" type="date" max="${dayKey()}" value="${esc(p.birth)}"></label><label>병력<textarea name="history" maxlength="1000" rows="3" placeholder="질환명·수술 이력 등">${esc(p.history)}</textarea></label></div></fieldset><fieldset><legend>02 돌봄 상태 · 10개 항목</legend><p class="muted">각 항목의 현재 상태를 확인해 주세요. 새 등록의 선택값은 시연용 기본값입니다.</p><div class="form-grid">${fields.map(([k,l,o])=>`<label>${l} *${o?`<select name="${k}">${o.map((v,i)=>`<option value="${i}" ${p[k]===i?'selected':''}>${v}</option>`).join('')}</select>`:`<input name="${k}" type="number" min="0" max="3650" step="1" required value="${p[k]}"><small>0~3650일</small>`}</label>`).join('')}</div></fieldset><fieldset><legend>03 관리자 한줄 평</legend><label>한줄 평 (선택, 최대 160자)<textarea name="comment" maxlength="160" rows="2" placeholder="비워 두면 점수에 따른 자동 설명이 표시됩니다.">${esc(p.comment)}</textarea></label><small>직접 작성한 평은 자동 설명과 구분되어 표시됩니다.</small></fieldset><div class="actions form-actions"><span id="dirty-status">저장된 정보 기준</span><button type="button" data-action="cancel">취소</button><button type="submit" class="primary">${editId?'수정 내용 저장':'대상자 등록'}</button></div></form>`;}
function render(focus=true){document.querySelectorAll('nav [data-nav]').forEach(b=>{const active=b.dataset.nav===page||(page==='detail'&&b.dataset.nav==='people');b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');b.hidden=b.dataset.nav==='form'&&role!=='admin';});$('#content').innerHTML=({dashboard,people:peoplePage,detail,form:formPage,analysis}[page]||dashboard)();strip();if(page==='people')updateTable();currentURL=location.href;if(focus){$('#content').focus();window.scrollTo(0,0);}}
function commitRoute(next,personId,editing=false){if(personId)selectedId=personId;page=next;editId=editing?selectedId:null;dirty=false;history.pushState(null,'',`#${next}/${encodeURIComponent(selectedId)}${editing?'/edit':''}`);render();}
function guard(action){if(dirty){pending=action;$('#leave-dialog').showModal();$('#keep-editing').focus();}else action();}
function navigate(next){guard(()=>{commitRoute(next);if(next==='people')syncFilters();});}
$('#keep-editing').onclick=()=>{$('#leave-dialog').close();pending=null;};
$('#discard-edit').onclick=()=>{dirty=false;$('#leave-dialog').close();const action=pending;pending=null;action?.();};
function persist(next){try{localStorage.setItem(storageKey,JSON.stringify(next));people=next;return true;}catch{return false;}}
function syncFilters(){const q=new URLSearchParams({q:query,type:filter,order,visits:visitsOnly?'1':'0'});history.replaceState(null,'',`#people/${encodeURIComponent(selectedId)}?${q}`);currentURL=location.href;}
function readRoute(){const [route,params='']=location.hash.slice(1).split('?'),[next,id,edit]=route.split('/');const q=new URLSearchParams(params);if(id&&people.some(p=>p.id===decodeURIComponent(id)))selectedId=decodeURIComponent(id);page=['dashboard','people','detail','analysis','form'].includes(next)?next:'dashboard';if(page==='form'&&role!=='admin')page='people';editId=page==='form'&&edit==='edit'?selectedId:null;if(page==='people'){query=q.get('q')||'';filter=q.get('type')||'';order=q.get('order')||'score';visitsOnly=q.get('visits')==='1';}render();}
window.addEventListener('popstate',()=>{if(dirty){const destination=location.href;history.pushState(null,'',currentURL);guard(()=>{history.pushState(null,'',destination);readRoute();});}else readRoute();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
$('#role').addEventListener('change',e=>{const value=e.target.value;e.target.value=role;guard(()=>{role=value;$('#role').value=role;commitRoute(page==='form'?'people':page);toast(role==='admin'?'관리자 시연 모드입니다. 실제 인증 기능은 없습니다.':'조회 모드에서는 편집할 수 없습니다.');});});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.nav){navigate(b.dataset.nav);return;}if(b.dataset.person){guard(()=>commitRoute('detail',b.dataset.person));return;}switch(b.dataset.action){case 'edit':if(role==='admin')guard(()=>commitRoute('form',selectedId,true));break;case 'cancel':navigate(editId?'detail':'people');break;case 'clear':query='';filter='';visitsOnly=false;order='score';render(false);syncFilters();$('#search').focus();break;case 'visits':guard(()=>{visitsOnly=true;query='';filter='';commitRoute('people');syncFilters();});break;case 'remove-photo':photoDraft='';dirty=true;$('#photo').value='';$('#photo-preview').innerHTML=portrait({name:'대상자',photo:''},true);$('#dirty-status').textContent='저장하지 않은 변경사항';break;case 'visit':if(role!=='admin')return;const p=selected(),next=people.map(v=>v.id===p.id?{...v,visited:v.visited===dayKey()?'':dayKey()}:v);if(persist(next)){render(false);toast('오늘의 방문 기록을 변경했습니다.');}else toast('저장 공간을 사용할 수 없어 방문 기록을 저장하지 못했습니다. 다시 시도해 주세요.');break;}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;updateTable();syncFilters();}if(e.target.closest('#person-form')){dirty=true;$('#dirty-status').textContent='저장하지 않은 변경사항';e.target.setCustomValidity?.('');}});
document.addEventListener('change',async e=>{if(e.target.id==='filter'){filter=e.target.value;updateTable();syncFilters();}if(e.target.id==='order'){order=e.target.value;updateTable();syncFilters();}if(e.target.id==='visits-only'){visitsOnly=e.target.checked;updateTable();syncFilters();}if(e.target.id==='analysis-person'){selectedId=e.target.value;history.replaceState(null,'',`#analysis/${encodeURIComponent(selectedId)}`);currentURL=location.href;render(false);$('#analysis-person').focus();}if(e.target.id==='photo'){const file=e.target.files[0];if(!file)return;const error=$('#photo-error');error.textContent='';if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){error.textContent='JPG·PNG·WebP 형식의 2MB 이하 사진을 선택해 주세요.';e.target.value='';return;}try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const ratio=Math.min(1,360/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();if(!$('#photo-preview')||!e.target.isConnected||e.target.files[0]!==file)return;photoDraft=canvas.toDataURL('image/jpeg',0.82);$('#photo-preview').innerHTML=portrait({name:'미리보기',photo:photoDraft},true);dirty=true;}catch{error.textContent='사진을 읽을 수 없습니다. 다른 사진을 선택해 주세요.';}}});
document.addEventListener('submit',e=>{if(e.target.id!=='person-form')return;e.preventDefault();if(role!=='admin')return;const f=e.target,d=new FormData(f),name=String(d.get('name')).trim();if(!name){f.elements.name.setCustomValidity('공백이 아닌 이름을 입력해 주세요.');f.elements.name.reportValidity();return;}const p={...(editId?selected():{}),id:editId||'p-'+Date.now(),photo:photoDraft,visited:editId?selected().visited:'',updated:new Date().toISOString(),...Object.fromEntries(['name','area','gender','birth','address','phone','contact','history','comment'].map(k=>[k,String(d.get(k)||'').trim()])),...Object.fromEntries(fields.map(([k])=>[k,Number(d.get(k))]))};if(!validPerson(p))return;const next=editId?people.map(v=>v.id===editId?p:v):[...people,p];if(!persist(next)){$('#save-error').textContent='브라우저 저장 공간이 부족하거나 저장이 차단되었습니다. 입력 내용은 유지됩니다. 사진 크기를 줄이거나 저장을 다시 시도해 주세요.';$('#save-error').scrollIntoView({block:'center'});return;}dirty=false;commitRoute('detail',p.id);toast('대상자 프로필과 한줄 평을 저장했습니다.');});
$('.brand').onclick=e=>{e.preventDefault();navigate('dashboard');};
$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
readRoute();
